---
name: Release->Build and Publish to GHRC
# yamllint disable rule:line-length

on:
  release:
    types: [published]

# set the run-name 
run-name: ${{ github.ref_name }} -> Release->Build and Publish to GHRC (
  ${{ github.run_attempt }}
  )

# Defines two custom environment variables for the workflow. 
# These are used for the Container registry domain, 
#  and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
            
jobs:

  output_debug_info:
    name: Output debug info
    runs-on: ubuntu-latest
    steps:

    - name: Get current date and time
      id: datetime
      run: |
        datetime=$(date +'%Y-%m-%dT%H-%M-%SZ')
        echo "datetime=$datetime" >> $GITHUB_OUTPUT

    - name: Display Run Name
      run: echo ${{ steps.datetime.outputs.datetime }}

    
  build_and_publish:
    name: Build artifacts and publish to ghrc
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.0

      
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}      

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2    


    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ github.repository }}


    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
