---
name: Build -> Packages (wheel, tar.gz)
# yamllint disable-line rule:line-length

on:
  workflow_dispatch:

# set the run-name 
run-name: ${{ github.ref_name }} -> Build Packages (
  ${{ github.run_attempt }}
  )


jobs:
  build:
    name: Build packages
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.0
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11
    
    - name: Update pip and install hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    
    - name: Hatch build
      run: hatch build

    - name: Archive all artifacts in dist/
      uses: actions/upload-artifact@v3.1.3
      with:
        name: dist
        path: dist/

      
