---
name: Build -> artifacts (wheel, tar.gz)
# yamllint disable-line rule:line-length

on:
  workflow_dispatch:

# set the run-name 
run-name: ${{ github.ref_name }} -> Build Artifacts (
  ${{ github.run_attempt }}
  )


jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:

    - name: Checkout
      uses: actions/checkout@v4.1.0
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4.7.0
      with:
        python-version: 3.11
    
    - name: Update pip and install hatch
      run: |
        python -m pip install --upgrade pip
        pip install hatch

    - name: Get version
      id: get_version
      run: |
        export version=$(hatch version)
        echo "version=$version" >> $GITHUB_OUTPUT
    
    - name: Hatch build
      run: hatch build

    - name: Archive all artifacts in dist/
      uses: actions/upload-artifact@v3.1.3
      with:
        name: dist-v${{ steps.get_version.outputs.version }}
        path: dist/

      
