---
name: Debug->dump env and context
#yamllint disable

on:
  workflow_dispatch:

run-name: ${{ github.ref_name }} -> dump env and context (
  ${{ github.run_attempt }}
  )
    
jobs:

  debug:
    
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Get current date and time
        id: datetime
        run: |
          datetime=$(date +'%Y-%m-%dT%H-%M-%SZ')
          echo "datetime=$datetime" >> $GITHUB_OUTPUT

      - name: Display Run Name
        run: echo ${{ steps.datetime.outputs.datetime }}

      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"